# Generated by scripts/gen-research-sdk.ts. Do not edit by hand.
from typing import Literal, Mapping

import pandas as pd


class _ChartResult:
    ...


class _DataApi:
    # Load a platform-governed historical series as a date-sorted pandas DataFrame.
    # DataFrame columns: date: datetime64[ns], value: float64
    def series(
        self,
        asset_type: Literal["stock", "etf", "index", "future"],
        identifier: str,
        *,
        start: str,
        end: str,
        measure: str = "market.adjusted_close",
        frequency: Literal["daily", "monthly"] = "daily",
        transform: Literal["level", "difference", "simple_return", "percent_change", "year_over_year"] = "level",
        partial_period: Literal["exclude", "include"] = "exclude",
    ) -> pd.DataFrame: ...



class _ChartsApi:
    # Create a native interactive line chart.
    def line(
        self,
        frame: pd.DataFrame,
        *,
        x: str,
        y: str | list[str],
        title: str | None = None,
        labels: Mapping[str, str] | None = None,
    ) -> _ChartResult: ...

    # Create a native interactive area chart.
    def area(
        self,
        frame: pd.DataFrame,
        *,
        x: str,
        y: str | list[str],
        title: str | None = None,
        labels: Mapping[str, str] | None = None,
    ) -> _ChartResult: ...

    # Create a native interactive bar chart.
    def bar(
        self,
        frame: pd.DataFrame,
        *,
        x: str,
        y: str | list[str],
        title: str | None = None,
        labels: Mapping[str, str] | None = None,
    ) -> _ChartResult: ...

    # Create a native interactive scatter chart.
    def scatter(
        self,
        frame: pd.DataFrame,
        *,
        x: str,
        y: str,
        title: str | None = None,
        labels: Mapping[str, str] | None = None,
    ) -> _ChartResult: ...



data: _DataApi
charts: _ChartsApi
