import type { zhFactor } from '../zh/factor';

// English mirror of zhFactor (structurally identical — enforced by typeof).
export const enFactor: typeof zhFactor = {
  agentLabel: 'Agent',
  libraryTab: 'Library',
  newFactor: 'New',

  unnamedNew: 'New factor (unsaved)',
  noneSelected: 'No factor selected',

  placeholderQa:
    'Ask about this preset factor — e.g. "is IC 0.03 strong?", "what horizon suits it?" — Enter to send',
  placeholderCompositeQa:
    'Ask about this composite — e.g. "are the components redundant?", "how should I read composite IC?" — Enter to send',
  placeholderAuthor:
    'Describe the factor you want, e.g. "earnings yield 1/PE", "small cap"; or keep chatting to refine — Enter to send',

  chatEmptyQa:
    'This is a preset factor (read-only code, see the middle editor). Ask anything about it or the analysis — the Agent only answers, it does not edit the code; to tweak parameters into a variant, click "Copy as custom" above the editor.',
  chatEmptyComposite:
    'This is a multi-factor composite (see its definition in the middle). Ask about directions, correlation, or report interpretation; the Agent answers questions without silently changing the composition.',
  chatEmptyAuthor:
    'Tell the Agent the factor you want (valuation / size / liquidity / money flow / price momentum & volatility) and it writes the code into the middle editor. Financial-statement detail (ROE growth, etc.) has no data yet.',

  presetGroup: 'Preset factors',
  customGroup: 'Custom factors',
  customEmpty: 'None yet — write one with the Agent',
  compositeGroup: 'Multi-factor composites',
  compositeEmpty: 'No composites yet',
  compositeCreate: 'New multi-factor composite',
  compositeCreateTitle: 'New multi-factor composite',
  compositeEditTitle: 'Edit multi-factor composite',
  compositeName: 'Name',
  compositeNamePlaceholder: 'e.g. Quality + value',
  compositeStandardizationLabel: 'Cross-sectional standardization',
  compositeStandardization: { rank: 'Rank', zscore: 'Z-score' },
  compositeComponents: 'Component factors (2–5)',
  compositeCount: '{{count}} / 5',
  compositeFactorPlaceholder: 'Select a factor',
  compositeDirection: {
    positive: 'Positive (higher is better)',
    negative: 'Negative (lower is better)',
  },
  compositeAddFactor: 'Add component',
  compositeEqualWeight: 'Equal weight',
  compositeEqualOnlyHint:
    'V1 is equal-weight only: standardize on the common universe, align directions, then average. This avoids fitting weights on the same explore sample.',
  compositeMethodHint:
    'Each period keeps stocks covered by every component. Component code, directions, and composition rules are frozen with the report.',
  compositeMethodologySpec: '{{count}} components · {{standardization}} · equal weight',
  compositeCreated: 'Multi-factor composite created',
  compositeUpdated: 'Multi-factor composite updated',
  compositeDeleteTitle: 'Delete multi-factor composite?',
  compositeDeleteContent: 'Delete “{{name}}”? Historical reports will remain available.',
  kindComposite: 'Composite',
  edit: 'Edit',
  save: 'Save',
  deleteTitle: 'Delete',
  deleteConfirmTitle: 'Confirm delete',
  deleteConfirmContent: 'Delete custom factor "{{name}}"? This cannot be undone.',
  deleteOk: 'Delete',
  cancel: 'Cancel',

  presetReadonly: 'Preset factor, code is read-only',
  forkToCustom: 'Copy as custom',
  editorLoading: 'Loading editor…',
  strategyKey: 'Strategy key',
  strategyKeyPlaceholder: 'earnings_yield',
  strategyKeyDraftHint:
    'Generated by the Agent and editable before confirmation; only finalized keys are available in Strategy',
  strategyKeyInvalid: 'Use lowercase letters, digits, and underscores only, starting with a letter',
  strategyKeyFinalize: 'Confirm and lock',
  strategyKeyConfirm: 'Use {{key}}? It cannot be changed after it is locked.',
  strategyKeyFinalized: 'Strategy key locked',
  strategyKeyLocked: 'Locked',

  log: 'Log',
  logEmpty: 'Run an analysis to see the log here (system progress + your console output)',

  pickPrompt: '← Pick a factor, or have the Agent write one, then run analysis',

  freq: 'Frequency',
  range: 'Range',
  neutralLabel: 'Neutralize',
  neutralNone: 'None',
  neutralSize: 'Size',
  neutralSizeIndustry: 'Size + industry',
  neutralSizeTag: '·size-neut',
  neutralSizeIndustryTag: '·size+ind-neut',
  paramsSummary: '{{frequency}} · {{start}} to {{end}} · {{neutral}}',
  paramsSettings: 'Analysis settings',
  paramsMore: 'More settings',
  paramsChanged: 'Parameters or code changed; running will create a new report',
  reportOutdatedCode: 'Code changed. This report still uses the previous code; run again.',
  reportOutdatedParams:
    'Parameters changed. This report still uses the previous parameters; run again.',
  reportOutdatedBoth: 'Code and parameters changed. This report is out of date; run again.',
  methodologyUniverse: 'Universe and missing data',
  minimumListingDays: 'Minimum listing days',
  liquidityDropPercent: 'Drop least liquid',
  minimumCandidates: 'Minimum sample size',
  minimumWindowCoverage: 'Minimum window coverage',
  excludeRiskWarnings: 'Exclude ST / risk warnings',
  excludePendingDelisting: 'Exclude delisting-period stocks',
  methodologyOutliers: 'Outlier handling',
  factorExposureOutlier: 'Factor exposure',
  forwardReturnOutlier: 'Forward return',
  outlierNone: 'None',
  outlierWinsor: 'Winsorize 1%',
  outlierMad: 'MAD clipping',
  methodologyCosts: 'Per-side trading costs',
  commissionPerSide: 'Commission',
  stampDutySellSide: 'Sell stamp duty',
  slippagePerSide: 'Slippage',

  discardConfirmTitle: 'Discard changes that have not been run?',
  discardConfirmContent:
    'The current code or analysis parameters changed. Continuing will discard those changes.',
  discardConfirmOk: 'Discard changes',
  historyDiscardTitle: 'Restore the historical report parameters?',
  historyDiscardContent:
    'The current analysis parameters changed. Opening this report will restore its parameters.',
  historyDiscardOk: 'Open report',
  agentCodeConflict:
    'The Agent generated new code, but you edited during the turn, so it has not been applied.',
  keepMyCode: 'Keep my changes',
  applyAgentCode: 'Apply Agent code',

  corrTrigger: 'Correlation matrix',
  corrTitle: 'Factor correlation matrix',
  corrSelectPlaceholder: 'Pick 2–8 factors',
  corrRun: 'Compute',
  corrHint:
    'Pairwise cross-sectional Spearman, averaged per {{per}}, over {{startYear}}–{{endYear}} (follows the params bar). Includes a fixed “size” column to catch cap bets',
  corrRunning: 'Computing… (windowed factors are slow; live progress omitted)',
  corrCap:
    'Mean over {{periods}} {{per}}s · red = positive (redundant) · blue = negative · diagonal = 1',
  corrEmpty: 'Pick at least 2 factors, then Compute',
  run: 'Run analysis',
  rerunShort: 'Run again',
  running: 'Running',
  rerun: 'Run again with these parameters',
  historyButton: 'History',
  historyTitle: 'Report history',
  historyEmpty: 'No reports yet',
  historyRankIc: 'Rank IC {{value}}',
  phase: {
    explore: 'Explore',
    legacy: 'Legacy',
    holdoutSealed: 'Holdout · sealed',
    holdoutRevealed: 'Holdout · revealed',
  },
  status: {
    running: 'Running',
    done: 'Completed',
    error: 'Failed',
    stale: 'Interrupted',
  },
  unitWeek: 'week',
  unitMonth: 'month',

  researchSummary:
    '{{tests}} explore variants · {{reports}} completed reports · about {{falsePositives}} random false positives at 5%',
  researchSummaryHelp:
    'Re-running the same code, parameters, and criterion counts as one variant; failed/interrupted jobs and holdouts are excluded. The false-positive figure is a risk reminder, not a statistical correction.',
  researchCardTitle: 'Pre-run research card',
  researchModeHypothesis: 'Test a hypothesis',
  researchModeExploratory: 'Pure exploration',
  hypothesisPlaceholder: 'State the hypothesis before seeing the result',
  rationalePlaceholder: 'Economic or behavioral rationale (optional)',
  directionPositive: 'Expected positive',
  directionNegative: 'Expected negative',
  criterionRankIc: 'Mean Rank IC',
  criterionIcir: 'Annualized ICIR',
  criterionNetLs: 'Net long-short annualized',
  exploratoryNotice:
    'This run is labeled pure exploration and cannot later be presented as a prior hypothesis.',
  confirmRun: 'Freeze card and run',
  holdoutConfirmTitle: 'Validate on the formal holdout?',
  holdoutConfirmContent:
    'The frozen code and parameters will be tested from {{start}} to {{end}}. The result stays sealed after computation.',
  runHoldout: 'Validate holdout',
  holdoutFrozenCode: 'Frozen code {{hash}}',
  holdoutPreset: 'Pre-registered: {{direction}} · {{criterion}}',
  holdoutCodeChanged:
    'The editor code has changed: this validates the code snapshot frozen in the report, not the current code.',
  holdoutReason: {
    not_explore: 'Only explore reports can start a holdout validation',
    not_done: 'The report must finish before starting a holdout validation',
    missing_hypothesis: 'Holdout unavailable: the research card is not in hypothesis mode',
    outside_explore_window:
      'Holdout unavailable: the explore range crosses into the holdout period',
    insufficient_periods: 'Holdout unavailable: not enough rebalance periods in the holdout',
    already_observed: 'Holdout unavailable: this code has already observed the holdout data',
    already_exists: 'This report already has a formal holdout',
  },
  holdoutSealed:
    'The holdout computation is complete and still sealed. Revealing it cannot restore an unobserved state.',
  revealHoldout: 'Reveal result',
  revealConfirmTitle: 'Reveal the holdout result?',
  revealConfirmContent:
    'Revealing records an irreversible first-view time. This data will no longer be unobserved.',
  holdoutCriterionPassed: 'Primary criterion met · first revealed {{time}}',
  holdoutCriterionMissed: 'Primary criterion not met · first revealed {{time}}',

  computing:
    'Computing… the report is already in history, so you can refresh or switch factors · live log in the middle "Log"',
  runPrompt: 'Set the frequency / range, then click "Run analysis"',
  sample: 'Sample {{periods}} {{per}} · {{startYear}}–{{endYear}}',
  methodologyTitle: 'Methodology and reproducibility',
  dataCutoff: 'Data cutoff {{date}}',
  reproducibilityHash: 'Code SHA-256 {{hash}}',
  periodCoverage: '{{analyzed}} / {{considered}} valid periods',
  notAvailable: 'unavailable',
  stageFactorValue: 'Factor values',
  stageQuotes: 'Formation/forward quotes',
  stageListingAge: 'Listing age',
  stageRiskWarning: 'ST/risk warning',
  stagePendingDelisting: 'Delisting period',
  stageLiquidity: 'Liquidity',
  universeSpec:
    'Listed ≥{{days}} days · drop least-liquid {{liquidity}}% · ≥{{candidates}} names per period',
  outlierSpec: 'Factor exposure: {{exposure}} · forward return: {{returns}}',
  costSpec:
    'Commission {{commission}}bp/side · stamp {{stamp}}bp/sell · slippage {{slippage}}bp/side',
  historicalStatusSpec: 'ST/risk-warning filter: {{risk}} · delisting-period filter: {{delisting}}',
  enabled: 'enabled',
  disabled: 'disabled',
  windowCoverageAudit:
    '{{window}}-day window · minimum {{minimum}} · mean {{mean}} · {{dropped}} observations dropped for coverage',
  historicalFiltersUnavailable:
    'Reliable historical data is unavailable for: {{filters}}. The report marks this explicitly and does not backfill history with current status.',
  unavailableFilter: {
    risk_warning: 'ST/risk warning',
    pending_delisting: 'pending delisting',
    negative_equity: 'negative equity',
    long_suspension: 'long suspension',
  },
  outlier: {
    none: 'none',
    winsor: 'winsorize 1%',
    mad: 'MAD clipping',
  },
  weightEqual: 'Equal weight',
  weightMktcap: 'Market-cap weight',

  dirUp: 'Positive · long the top decile',
  dirDown: 'Negative · long the bottom decile',
  dirFlat: 'Direction not significant',

  decileCap:
    'X-axis D1 (lowest factor value) → D{{n}} (highest); Y-axis each decile\'s annualized "next {{per}}" return — a rising ramp = momentum, a falling ramp = reversal.',
  decileCapMktcap:
    ' Market-cap weight shows whether large caps actually earn it (equal weight is easily amplified by small caps).',

  metricIcMean: 'Rank IC mean',
  metricIcMeanHint: 'sign = direction · magnitude = strength',
  metricIcir: 'ICIR (annualized)',
  metricIcirHint: 'IC stability',
  metricIcPos: 'IC>0 rate',
  metricIcPosHint: 'share of {{per}}s with a consistent direction',
  metricLsAnn: 'Long-short D{{n}}−D1 ann.',
  metricLsAnnHint: 'pure factor return',
  metricLsSharpe: 'Long-short Sharpe',
  metricLsMdd: 'Long-short max drawdown',
  metricTopTurnover: 'Top-decile {{per}} turnover',
  metricTopTurnoverHint: 'higher = heavier friction',

  lsNavTitle: 'Long-short NAV · gross vs net',
  lsNavCap:
    'Equal-weight long-short; the net line deducts, each rebalance, both legs’ turnover × round-trip cost per name (commission + stamp + slippage ≈ 30bps). Shorting is constrained in A-shares, so the long-short is hypothetical — use this to compare factors’ survivability',
  lsNavGross: 'Gross',
  lsNavNet: 'Net',
  metricLsNetAnn: 'Net long-short (D10−D1) annualized',
  metricLsNetAnnHint: 'Long-short return after trading cost',
  metricLsNetSharpe: 'Net Sharpe',
  metricLsNetMdd: 'Net max drawdown',

  icDecayTitle: "IC decay · the factor's holding period",
  icDecayCap: 'X-axis forward trading days, Y-axis Rank IC — {{hint}}',
  decayPeak: '|IC| peaks at {{days}} days · {{trend}}',
  decayTrendSlow: 'stronger further out (slow factor, hold long)',
  decayTrendFast: 'stronger at the short end, then decays (fast factor, hold short)',

  heatmapTitle: "Decile × forward horizon · each decile's return across holding periods",
  heatmapCap:
    'Cell = average daily forward return (‱ bps of 10k, normalized by holding days, comparable across rows), red up / green down. See which horizon makes D1→D{{n}} most monotonic and whether the signal decays.',

  kindPrice: 'Price',
  kindFundamental: 'Fundamental',
  kindMoneyflow: 'Money flow',
  kindCustom: 'Custom',

  // Chart axis / tooltip labels (decile bar chart, IC-decay line, quantile heatmap).
  decileD1Low: 'D1 low',
  decileDnHigh: 'D{{n}} high',
  decileTipAnn: 'Ann. return {{pct}}%',
  decileTipSharpe: 'Sharpe {{sharpe}} · end NAV {{nav}}',
  icDecayTipHorizon: '{{days}}d forward',
  days: '{{days}}d',
  qhCorner: 'Horizon\\Decile',

  // Store-side messages (surfaced via i18n.t in factor-store.ts).
  errorPrefix: 'Error: {{message}}',
  saveFailed: 'failed to save the factor, cannot start the conversation',
  requestFailed: 'request failed',
  turnStopped: '(stopped this reply)',
  unnamedFactor: 'Untitled factor',
  analysisInterrupted: 'Analysis interrupted (server restarted), please retry',
  analysisFailed: 'Analysis failed',

  // Built-in preset factor display names, keyed by catalog slug (apps/api/src/factor/builtin-factors.ts).
  builtin: {
    mom: 'Momentum (60d, skip 5)',
    mom_12_1: 'Momentum (12-1 month)',
    rev: 'Reversal (5d)',
    vol: 'Volatility (20d)',
    vol120: 'Volatility (120d)',
    abturn: 'Abnormal turnover (21d/252d)',
    amihud: 'Amihud illiquidity (20d)',
    turn20: 'Turnover level (20d mean)',
    roe_stability: 'ROE stability (504d)',
    ep: 'Earnings yield (1/PE_TTM)',
    bp: 'Book-to-market (1/PB)',
    dv: 'Dividend yield (%)',
    size: 'Size (ln total market cap)',
    roe: 'ROE quality (%)',
    gross_margin: 'Gross margin (%)',
    mf_net_main: 'Main-force net inflow (10k CNY)',
    mf_net_total: 'Total net inflow (10k CNY)',
  },
};
