/** Curated static surface for packages fixed in research-py-v1. */
export const RESEARCH_LANGUAGE_LIBRARY_STUBS: Readonly<Record<string, string>> = {
  'pandas/__init__.pyi': `from typing import Any, Callable, Generic, Iterable, Iterator, Mapping, Sequence, TypeVar, overload

_T = TypeVar("_T")

class Index(Generic[_T], Sequence[_T]):
    def __getitem__(self, key: int) -> _T: ...
    def __len__(self) -> int: ...
    def tolist(self) -> list[_T]: ...

class DatetimeIndex(Index[Any]): ...

class Series(Generic[_T]):
    def __init__(self, data: Any = None, index: Any = None, dtype: Any = None, name: str | None = None, copy: bool | None = None) -> None: ...
    name: str | None
    dtype: Any
    shape: tuple[int]
    @overload
    def __getitem__(self, key: int) -> _T: ...
    @overload
    def __getitem__(self, key: slice) -> Series[_T]: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __add__(self, other: Any) -> Series[Any]: ...
    def __sub__(self, other: Any) -> Series[Any]: ...
    def __mul__(self, other: Any) -> Series[Any]: ...
    def __truediv__(self, other: Any) -> Series[Any]: ...
    def astype(self, dtype: Any) -> Series[Any]: ...
    def copy(self, deep: bool = True) -> Series[_T]: ...
    def corr(self, other: Series[Any], method: str = "pearson", min_periods: int | None = None) -> float: ...
    def cov(self, other: Series[Any], min_periods: int | None = None) -> float: ...
    def diff(self, periods: int = 1) -> Series[Any]: ...
    def dropna(self, *, inplace: bool = False) -> Series[_T] | None: ...
    def fillna(self, value: Any = None, *, method: str | None = None, inplace: bool = False) -> Series[_T] | None: ...
    def head(self, n: int = 5) -> Series[_T]: ...
    def mean(self, *, skipna: bool = True) -> float: ...
    def median(self, *, skipna: bool = True) -> float: ...
    def pct_change(self, periods: int = 1, *, fill_method: str | None = None) -> Series[Any]: ...
    def quantile(self, q: float = 0.5) -> float: ...
    def rename(self, name: str, *, inplace: bool = False) -> Series[_T] | None: ...
    def rolling(self, window: int, min_periods: int | None = None, center: bool = False) -> Rolling: ...
    def shift(self, periods: int = 1) -> Series[_T]: ...
    def std(self, *, skipna: bool = True, ddof: int = 1) -> float: ...
    def sum(self, *, skipna: bool = True) -> Any: ...
    def tail(self, n: int = 5) -> Series[_T]: ...
    def to_frame(self, name: str | None = None) -> DataFrame: ...
    def to_list(self) -> list[_T]: ...
    def to_numpy(self, dtype: Any = None) -> Any: ...

class Rolling:
    def apply(self, func: Callable[..., Any], raw: bool = False) -> Series[Any] | DataFrame: ...
    def corr(self, other: Any = None) -> Series[Any] | DataFrame: ...
    def cov(self, other: Any = None) -> Series[Any] | DataFrame: ...
    def mean(self) -> Series[Any] | DataFrame: ...
    def median(self) -> Series[Any] | DataFrame: ...
    def std(self, ddof: int = 1) -> Series[Any] | DataFrame: ...
    def sum(self) -> Series[Any] | DataFrame: ...

class DataFrame:
    def __init__(self, data: Any = None, index: Any = None, columns: Any = None, dtype: Any = None, copy: bool | None = None) -> None: ...
    columns: Index[str]
    index: Index[Any]
    dtypes: Series[Any]
    shape: tuple[int, int]
    @overload
    def __getitem__(self, key: str) -> Series[Any]: ...
    @overload
    def __getitem__(self, key: list[str]) -> DataFrame: ...
    @overload
    def __getitem__(self, key: Series[bool]) -> DataFrame: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __len__(self) -> int: ...
    def assign(self, **kwargs: Any) -> DataFrame: ...
    def astype(self, dtype: Any) -> DataFrame: ...
    def copy(self, deep: bool = True) -> DataFrame: ...
    def corr(self, method: str = "pearson", min_periods: int = 1, numeric_only: bool = False) -> DataFrame: ...
    def cov(self, min_periods: int | None = None, ddof: int = 1, numeric_only: bool = False) -> DataFrame: ...
    def diff(self, periods: int = 1, axis: int | str = 0) -> DataFrame: ...
    def drop(self, labels: Any = None, *, axis: int | str = 0, columns: Any = None, inplace: bool = False) -> DataFrame | None: ...
    def dropna(self, *, axis: int | str = 0, how: str = "any", subset: Sequence[str] | None = None, inplace: bool = False) -> DataFrame | None: ...
    def fillna(self, value: Any = None, *, method: str | None = None, inplace: bool = False) -> DataFrame | None: ...
    def groupby(self, by: Any = None, *, sort: bool = True, dropna: bool = True) -> DataFrameGroupBy: ...
    def head(self, n: int = 5) -> DataFrame: ...
    def join(self, other: DataFrame | Series[Any], on: str | list[str] | None = None, how: str = "left", lsuffix: str = "", rsuffix: str = "") -> DataFrame: ...
    def mean(self, axis: int | str = 0, *, skipna: bool = True, numeric_only: bool = False) -> Series[Any]: ...
    def merge(self, right: DataFrame, how: str = "inner", on: str | list[str] | None = None, left_on: Any = None, right_on: Any = None, suffixes: tuple[str, str] = ("_x", "_y")) -> DataFrame: ...
    def pct_change(self, periods: int = 1, *, fill_method: str | None = None) -> DataFrame: ...
    def pivot(self, *, columns: Any, index: Any = None, values: Any = None) -> DataFrame: ...
    def pivot_table(self, values: Any = None, index: Any = None, columns: Any = None, aggfunc: Any = "mean") -> DataFrame: ...
    def rename(self, mapper: Any = None, *, index: Any = None, columns: Mapping[str, str] | Callable[[str], str] | None = None, inplace: bool = False) -> DataFrame | None: ...
    def reset_index(self, level: Any = None, *, drop: bool = False, inplace: bool = False, names: Any = None) -> DataFrame | None: ...
    def rolling(self, window: int, min_periods: int | None = None, center: bool = False) -> Rolling: ...
    def set_index(self, keys: str | list[str], *, drop: bool = True, inplace: bool = False) -> DataFrame | None: ...
    def shift(self, periods: int = 1, axis: int | str = 0) -> DataFrame: ...
    def sort_index(self, *, axis: int | str = 0, ascending: bool = True, inplace: bool = False) -> DataFrame | None: ...
    def sort_values(self, by: str | list[str], *, axis: int | str = 0, ascending: bool | list[bool] = True, inplace: bool = False) -> DataFrame | None: ...
    def std(self, axis: int | str = 0, *, skipna: bool = True, ddof: int = 1, numeric_only: bool = False) -> Series[Any]: ...
    def sum(self, axis: int | str = 0, *, skipna: bool = True, numeric_only: bool = False) -> Series[Any]: ...
    def tail(self, n: int = 5) -> DataFrame: ...
    def to_dict(self, orient: str = "dict", *, into: Any = dict) -> dict[Any, Any] | list[dict[str, Any]]: ...
    def to_numpy(self, dtype: Any = None) -> Any: ...
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...

class DataFrameGroupBy:
    def agg(self, func: Any = None, **kwargs: Any) -> DataFrame: ...
    def apply(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> DataFrame | Series[Any]: ...
    def count(self) -> DataFrame: ...
    def mean(self, numeric_only: bool = False) -> DataFrame: ...
    def size(self) -> Series[int]: ...
    def sum(self, numeric_only: bool = False) -> DataFrame: ...

class Timestamp:
    def __init__(self, ts_input: Any = None, **kwargs: Any) -> None: ...
    def strftime(self, format: str) -> str: ...

def concat(objs: Iterable[DataFrame | Series[Any]], axis: int | str = 0, join: str = "outer", ignore_index: bool = False, keys: Sequence[Any] | None = None) -> DataFrame: ...
def date_range(start: Any = None, end: Any = None, periods: int | None = None, freq: str | None = None, tz: str | None = None) -> DatetimeIndex: ...
def isna(obj: Any) -> Any: ...
def notna(obj: Any) -> Any: ...
def read_csv(filepath_or_buffer: Any, **kwargs: Any) -> DataFrame: ...
def to_datetime(arg: Any, errors: str = "raise", format: str | None = None, unit: str | None = None) -> Any: ...
`,
  'numpy/__init__.pyi': `from typing import Any, Callable, Generic, Iterable, Sequence, TypeVar, overload

_T = TypeVar("_T")

class dtype(Generic[_T]): ...

class ndarray(Generic[_T]):
    shape: tuple[int, ...]
    dtype: dtype[_T]
    ndim: int
    size: int
    def __getitem__(self, key: Any) -> Any: ...
    def __len__(self) -> int: ...
    def astype(self, dtype: Any) -> ndarray[Any]: ...
    def copy(self) -> ndarray[_T]: ...
    def mean(self, axis: int | None = None) -> Any: ...
    def reshape(self, *shape: int) -> ndarray[_T]: ...
    def std(self, axis: int | None = None, ddof: int = 0) -> Any: ...
    def sum(self, axis: int | None = None) -> Any: ...
    def tolist(self) -> list[Any]: ...

nan: float
inf: float
pi: float

def abs(x: Any) -> Any: ...
def arange(start: float, stop: float | None = None, step: float = 1, dtype: Any = None) -> ndarray[Any]: ...
def array(object: Any, dtype: Any = None, copy: bool | None = None) -> ndarray[Any]: ...
def asarray(a: Any, dtype: Any = None) -> ndarray[Any]: ...
def clip(a: Any, a_min: Any, a_max: Any) -> Any: ...
def corrcoef(x: Any, y: Any = None, rowvar: bool = True) -> ndarray[Any]: ...
def diff(a: Any, n: int = 1, axis: int = -1) -> ndarray[Any]: ...
def exp(x: Any) -> Any: ...
def isfinite(x: Any) -> Any: ...
def isnan(x: Any) -> Any: ...
def linspace(start: float, stop: float, num: int = 50, endpoint: bool = True) -> ndarray[Any]: ...
def log(x: Any) -> Any: ...
def mean(a: Any, axis: int | None = None) -> Any: ...
def median(a: Any, axis: int | None = None) -> Any: ...
def percentile(a: Any, q: Any, axis: int | None = None) -> Any: ...
def polyfit(x: Any, y: Any, deg: int) -> ndarray[Any]: ...
def quantile(a: Any, q: Any, axis: int | None = None) -> Any: ...
def sqrt(x: Any) -> Any: ...
def std(a: Any, axis: int | None = None, ddof: int = 0) -> Any: ...
def sum(a: Any, axis: int | None = None) -> Any: ...
def where(condition: Any, x: Any = None, y: Any = None) -> Any: ...
def zeros(shape: int | Sequence[int], dtype: Any = float) -> ndarray[Any]: ...
def ones(shape: int | Sequence[int], dtype: Any = float) -> ndarray[Any]: ...
`,
  'matplotlib/__init__.pyi': `from . import pyplot as pyplot
`,
  'matplotlib/pyplot.pyi': `from typing import Any

def close(fig: Any = None) -> None: ...
def figure(*args: Any, **kwargs: Any) -> Any: ...
def plot(*args: Any, **kwargs: Any) -> list[Any]: ...
def scatter(*args: Any, **kwargs: Any) -> Any: ...
def hist(*args: Any, **kwargs: Any) -> Any: ...
def show(*args: Any, **kwargs: Any) -> None: ...
def subplots(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def title(label: str, **kwargs: Any) -> Any: ...
def xlabel(xlabel: str, **kwargs: Any) -> Any: ...
def ylabel(ylabel: str, **kwargs: Any) -> Any: ...
`,
};
