// Generated by scripts/sandbox/setup.ts from reference.ts. Do not edit by hand.

export interface FactorBar {
  readonly code: string;
  /** P/E */ readonly pe: number | null;
  /** P/E (TTM) */ readonly peTtm: number | null;
  /** P/B */ readonly pb: number | null;
  /** P/S */ readonly ps: number | null;
  /** P/S (TTM) */ readonly psTtm: number | null;
  /** Dividend yield % */ readonly dvRatio: number | null;
  /** Dividend yield (TTM) % */ readonly dvTtm: number | null;
  /** Total market cap (10k yuan) */ readonly totalMv: number | null;
  /** Float market cap (10k yuan) */ readonly circMv: number | null;
  /** Turnover rate % */ readonly turnoverRate: number | null;
  /** Main-force net inflow (10k yuan, exact for the day, null if missing) */ readonly netMain: number | null;
  /** Total net inflow (10k yuan, exact for the day, null if missing) */ readonly netTotal: number | null;
  /** Return on equity % (latest report with annDate ≤ today, point-in-time; null if none published) */ readonly roe: number | null;
  /** Return on assets % (latest report with annDate ≤ today, point-in-time; null if none published) */ readonly roa: number | null;
  /** Gross profit margin % (as-of, point-in-time; null if none published) */ readonly grossprofitMargin: number | null;
  /** Debt-to-assets ratio % (as-of, point-in-time; null if none published) */ readonly debtToAssets: number | null;
}
export interface FactorCtx {
  /** Adjusted (hfq) close window, [oldest … today] of n values; returns [] if history is insufficient. Declare window ≥ n in defineFactor. */
  history(n: number): number[];
  /** Trade dates (YYYYMMDD) for the window, aligned position-by-position with the closes — usable for suspension-gap checks. */
  history(n: number, field: 'date'): string[];
  /** Daily turnover amount history (thousand yuan), aligned with closes; null when unavailable. */
  history(n: number, field: 'amount'): (number | null)[];
  /** Free-float turnover-rate (%) history; null means unavailable that day. */
  history(n: number, field: 'turnoverRateF'): (number | null)[];
  /** Point-in-time ROE (%) history: each day carries the latest report announced on/before it (a step series jumping on announcement days); null before the first report. */
  history(n: number, field: 'roe'): (number | null)[];
  /** Point-in-time gross profit margin (%) history: each day carries the latest report announced on/before it; null before the first report. */
  history(n: number, field: 'grossprofitMargin'): (number | null)[];
  /** CSI All Share (000985.CSI) close history aligned with the stock-history dates; null when the benchmark has no exact-date close, never forward-filled. */
  history(n: number, field: 'marketClose'): (number | null)[];
}
export interface CustomFactor {
  /** Factor name (for display) */
  name: string;
  /** Required history length (trading days, including today). Declaring it enables ctx.history inside compute. */
  window?: number;
  /** Minimum fraction of market trading days required inside the declared window (0.1–1). */
  minCoverage?: number;
  /** Compute the factor value per stock: return a number, or null to drop the stock. Direction is revealed by the IC sign in analysis — don't pre-negate. */
  compute: (bar: FactorBar, ctx: FactorCtx) => number | null;
}
/** Define a factor. Usage: export default defineFactor({ name, window?, compute(bar, ctx) { … } }) */
export type DefineFactor = (factor: CustomFactor) => CustomFactor;

export type FactorV2Field =
  | 'etf.adjustedClose'
  | 'rates.cgb.yield.2y'
  | 'rates.cgb.yield.5y'
  | 'rates.cgb.yield.10y'
  | 'rates.cgb.yield.30y';
export type FactorV2AssetClass = 'equity' | 'fixed_income' | 'commodity';
export interface TimeSeriesFactorCtxV2 {
  /** Current point-in-time value for a declared field. */
  value(field: FactorV2Field): number | null;
  /** Value N observations before the current decision date. */
  lag(field: FactorV2Field, periods: number): number | null;
}
export interface AssetFactorV2 {
  version: 2;
  name: string;
  analysisKind: 'time_series' | 'panel';
  outputScope: 'asset';
  frequency: 'daily';
  inputs: FactorV2Field[];
  targetAssetClasses: FactorV2AssetClass[];
  /** Required trading-day history, including the current observation. */
  window: number;
  compute: (ctx: TimeSeriesFactorCtxV2) => number | null;
}
/** Define an asset-scope time-series or cross-asset panel factor with explicit point-in-time inputs. */
export type DefineFactorV2 = (factor: AssetFactorV2) => AssetFactorV2;
