from __future__ import annotations

from typing import TYPE_CHECKING, Any, Iterable, Protocol

if TYPE_CHECKING:
    from .python import AttrDict


# Structural inputs keep author helpers independent of the sandbox runtime.
class StrategyStockCapabilities(Protocol):
    @property
    def equity(self) -> float: ...

    @property
    def available_cash(self) -> float: ...

    def positions(self) -> list[AttrDict]: ...
    def adjusted_shares(self, code: str) -> float: ...
    def set_target_weight(self, code: str, weight: float) -> None: ...
    def set_target_weights(self, weights: dict[str, float]) -> None: ...
    def order_adjusted_shares(self, code: str, shares: float) -> None: ...
    def order_lots(self, code: str, lots: float) -> None: ...
    def close_position(self, code: str) -> None: ...
    def stop_loss_at_adjusted_price(self, code: str, price: float) -> None: ...
    def trailing_stop_by_fraction(self, code: str, percentage: float) -> None: ...
    def limit_buy_at_adjusted_price(self, code: str, price: float, shares: float) -> None: ...
    def take_profit_by_fraction(self, code: str, percentage: float) -> None: ...
    def cancel_conditional(self, code: str, kind: str | None = None) -> None: ...


class StrategyCapabilities(Protocol):
    @property
    def portfolio(self) -> AttrDict: ...

    @property
    def futures(self) -> AttrDict: ...

    @property
    def stock(self) -> StrategyStockCapabilities: ...

    @property
    def date(self) -> str: ...

    def load_cross_section(self, index_code: str | None = None) -> list[str]: ...
    def bar(self, code: str) -> AttrDict | None: ...
    def ensure_bars(self, codes: Iterable[str]) -> None: ...
    def bars(self, code: str, count: int) -> list[AttrDict]: ...
    def history(self, code: str, field: str, count: int) -> list[float]: ...
    def price(self, code: str) -> float | None: ...
    def list_days(self, code: str) -> int | None: ...
    def industry(self, code: str) -> str | None: ...
    def lhb_net(self, code: str) -> float | None: ...
    def factor(self, name: str, code: str) -> float | None: ...
