import type { FactorAnalysisKind } from './factor.js';

export const FACTOR_PYTHON_RUNTIME_VERSION = 'py-v1' as const;

export const FACTOR_PYTHON_ANALYSIS_KINDS = [
  'cross_sectional',
  'time_series',
  'panel',
] as const satisfies readonly FactorAnalysisKind[];

export const FACTOR_PYTHON_V2_FIELD_KEYS = [
  'etf.adjustedClose',
  'rates.cgb.yield.2y',
  'rates.cgb.yield.5y',
  'rates.cgb.yield.10y',
  'rates.cgb.yield.30y',
  'commodity.futures.annualizedLogCarry',
  'commodity.warehouseReceipt.volume',
] as const;

export type FactorPythonV2FieldKey = (typeof FACTOR_PYTHON_V2_FIELD_KEYS)[number];

/** Render the Python authoring surface consumed by the sandbox validator and Monaco/Pyright. */
export function renderFactorPythonSdkStub(): string {
  const fieldLiteral = FACTOR_PYTHON_V2_FIELD_KEYS.map((field) => JSON.stringify(field)).join(', ');
  return `# Generated by scripts/gen-factor-sdk.ts. Do not edit by hand.
from collections.abc import Callable, Sequence
from typing import Literal, TypeAlias, overload

Number: TypeAlias = int | float
FactorValue: TypeAlias = Number | None
FactorV2Field: TypeAlias = Literal[${fieldLiteral}]
FactorTargetAssetClass: TypeAlias = Literal["equity", "fixed_income", "commodity"]


class FactorBar:
    code: str
    pe: float | None
    pe_ttm: float | None
    pb: float | None
    ps: float | None
    ps_ttm: float | None
    dv_ratio: float | None
    dv_ttm: float | None
    total_mv: float | None
    circ_mv: float | None
    turnover_rate: float | None
    net_main: float | None
    net_total: float | None
    roe: float | None
    roa: float | None
    grossprofit_margin: float | None
    debt_to_assets: float | None


class CrossSectionalFactorContext:
    @overload
    def history(self, periods: int, field: Literal["close"] = "close") -> list[float]: ...
    @overload
    def history(self, periods: int, field: Literal["date"]) -> list[str]: ...
    @overload
    def history(
        self,
        periods: int,
        field: Literal[
            "amount", "turnover_rate_f", "roe", "grossprofit_margin", "market_close"
        ],
    ) -> list[float | None]: ...


class AssetFactorContext:
    def value(self, field: FactorV2Field) -> float | None: ...
    def lag(self, field: FactorV2Field, periods: int) -> float | None: ...


CrossSectionalCompute: TypeAlias = Callable[
    [FactorBar, CrossSectionalFactorContext], FactorValue
]
AssetCompute: TypeAlias = Callable[[AssetFactorContext], FactorValue]


class CrossSectionalFactor:
    def compute(self, callback: CrossSectionalCompute) -> CrossSectionalCompute: ...


class AssetFactor:
    def compute(self, callback: AssetCompute) -> AssetCompute: ...


class Factor:
    @classmethod
    def cross_sectional(
        cls,
        *,
        name: str,
        window: int | None = None,
        min_coverage: float | None = None,
    ) -> CrossSectionalFactor: ...

    @classmethod
    def time_series(
        cls,
        *,
        name: str,
        inputs: Sequence[FactorV2Field],
        target_asset_classes: Sequence[FactorTargetAssetClass],
        window: int,
    ) -> AssetFactor: ...

    @classmethod
    def panel(
        cls,
        *,
        name: str,
        inputs: Sequence[FactorV2Field],
        target_asset_classes: Sequence[FactorTargetAssetClass],
        window: int,
    ) -> AssetFactor: ...
`;
}
