import {
  RESEARCH_SDK_CONTRACT_V1,
  type ResearchSdkContractV1,
  type ResearchSdkFunctionContractV1,
} from './research-sdk-contract.js';
import {
  renderResearchSdkPythonParameter,
  researchSdkPythonReturnType,
} from './research-sdk-python-signature.js';

/** Render the Python typing surface used by both the sandbox artifact and Pyright workspace. */
export function renderResearchSdkPythonStub(
  sdk: ResearchSdkContractV1 = RESEARCH_SDK_CONTRACT_V1,
): string {
  const functionsByNamespace = new Map<string, ResearchSdkFunctionContractV1[]>();
  for (const contract of sdk.functions) {
    const functions = functionsByNamespace.get(contract.namespace) ?? [];
    functions.push(contract);
    functionsByNamespace.set(contract.namespace, functions);
  }
  const lines = [
    '# Generated by scripts/gen-research-sdk.ts. Do not edit by hand.',
    'from typing import Literal, Mapping',
    '',
    'import pandas as pd',
    '',
    '',
    'class _ChartResult:',
    '    ...',
  ];

  for (const [namespace, functions] of functionsByNamespace) {
    const className = `_${namespace[0]!.toUpperCase()}${namespace.slice(1)}Api`;
    lines.push('', '', `class ${className}:`);
    for (const contract of functions) {
      lines.push(...renderFunction(contract));
    }
  }

  lines.push('', '');
  for (const namespace of functionsByNamespace.keys()) {
    const className = `_${namespace[0]!.toUpperCase()}${namespace.slice(1)}Api`;
    lines.push(`${namespace}: ${className}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderFunction(contract: ResearchSdkFunctionContractV1): string[] {
  const lines = [`    # ${contract.descriptionEn}`];
  for (const note of contract.notesEn) {
    lines.push(`    # Note: ${note}`);
  }
  for (const example of contract.examples) {
    lines.push(`    # Example: ${example}`);
  }
  if (contract.returns.kind === 'dataframe') {
    const columns = contract.returns.columns
      .map((column) => `${column.name}: ${column.pythonType}`)
      .join(', ');
    lines.push(`    # DataFrame columns: ${columns}`);
  }
  lines.push(`    def ${contract.name}(`, '        self,');

  let keywordOnlyStarted = false;
  for (const parameter of contract.parameters) {
    if (parameter.keywordOnly && !keywordOnlyStarted) {
      lines.push('        *,');
      keywordOnlyStarted = true;
    }
    lines.push(`        ${renderResearchSdkPythonParameter(parameter)},`);
  }

  const returnType = researchSdkPythonReturnType(contract.returns);
  lines.push(`    ) -> ${returnType}: ...`, '');
  return lines;
}
