import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import {
  RESEARCH_SDK_CONTRACT_V1,
  type ResearchSdkFunctionContractV1,
  type ResearchSdkParameterContractV1,
} from '../packages/shared/src/research-sdk-contract.js';

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});

async function main(): Promise<void> {
  const outputPath = resolve(process.cwd(), 'apps/sandboxd/python/jixie_research_sdk.pyi');
  const generated = renderPythonStub();

  if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== generated) {
      throw new Error('Research SDK stub is stale. Run pnpm gen:research-sdk.');
    }
    return;
  }

  await writeFile(outputPath, generated);
}

function renderPythonStub(): string {
  const functionsByNamespace = new Map<string, ResearchSdkFunctionContractV1[]>();
  for (const contract of RESEARCH_SDK_CONTRACT_V1.functions) {
    const functions = functionsByNamespace.get(contract.namespace) ?? [];
    functions.push(contract);
    functionsByNamespace.set(contract.namespace, functions);
  }
  const lines = [
    '# Generated by scripts/gen-research-sdk.ts. Do not edit by hand.',
    'from typing import Literal, Mapping',
    '',
    'import pandas as pd',
    '',
    '',
    'class _ChartResult:',
    '    ...',
  ];

  for (const [namespace, functions] of functionsByNamespace) {
    const className = `_${namespace[0]!.toUpperCase()}${namespace.slice(1)}Api`;
    lines.push('', '', `class ${className}:`);
    for (const contract of functions) {
      lines.push(...renderFunction(contract));
    }
  }

  lines.push('', '');
  for (const namespace of functionsByNamespace.keys()) {
    const className = `_${namespace[0]!.toUpperCase()}${namespace.slice(1)}Api`;
    lines.push(`${namespace}: ${className}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderFunction(contract: ResearchSdkFunctionContractV1): string[] {
  const lines = [`    # ${contract.descriptionEn}`];
  if (contract.returns.kind === 'dataframe') {
    const columns = contract.returns.columns
      .map((column) => `${column.name}: ${column.pythonType}`)
      .join(', ');
    lines.push(`    # DataFrame columns: ${columns}`);
  }
  lines.push(`    def ${contract.name}(`, '        self,');

  let keywordOnlyStarted = false;
  for (const parameter of contract.parameters) {
    if (parameter.keywordOnly && !keywordOnlyStarted) {
      lines.push('        *,');
      keywordOnlyStarted = true;
    }
    lines.push(`        ${renderParameter(parameter)},`);
  }

  const returnType = contract.returns.kind === 'dataframe' ? 'pd.DataFrame' : '_ChartResult';
  lines.push(`    ) -> ${returnType}: ...`, '');
  return lines;
}

function renderParameter(parameter: ResearchSdkParameterContractV1): string {
  let pythonType: string;
  switch (parameter.type) {
    case 'enum':
      pythonType = `Literal[${parameter.values!.map((value) => JSON.stringify(value)).join(', ')}]`;
      break;
    case 'string':
    case 'date':
      pythonType = 'str';
      break;
    case 'dataframe':
      pythonType = 'pd.DataFrame';
      break;
    case 'string_or_string_list':
      pythonType = 'str | list[str]';
      break;
    case 'string_map':
      pythonType = 'Mapping[str, str]';
      break;
  }

  if (parameter.defaultValue === null) {
    pythonType = `${pythonType} | None`;
  }
  if (parameter.defaultValue === undefined) {
    return `${parameter.name}: ${pythonType}`;
  }
  const defaultValue =
    parameter.defaultValue === null ? 'None' : JSON.stringify(parameter.defaultValue);
  return `${parameter.name}: ${pythonType} = ${defaultValue}`;
}
