// Generated by scripts/sandbox/setup.ts from reference.ts. Do not edit by hand.
/** Adjusted (hfq) OHLC of a code on a day — the unit ctx.bars() returns. [📖 docs](/docs#OhlcBar) */
export interface OhlcBar {
  date: string;
  adjOpen: number;
  adjHigh: number;
  adjLow: number;
  adjClose: number;
  vol: number | null;
  amount: number | null;
}

/** Completed weekly/monthly OHLC series; windows are oldest-to-newest and indicators return null when data is insufficient. */
export interface TimeframeSeries {
  /** Last n completed-period bars, oldest to newest. */
  bars(n: number): OhlcBar[];
  /** Last n period values for a field, oldest to newest. */
  history(field: 'open' | 'high' | 'low' | 'close', n: number): number[];
  /** n-period simple moving average of closes. */
  sma(n: number): number | null;
  /** n-period exponential moving average of closes. */
  ema(n: number): number | null;
  /** n-period average true range; requires n+1 period bars. */
  atr(n: number): number | null;
  /** Highest field value over the last n periods. */
  highest(field: 'open' | 'high' | 'low' | 'close', n: number): number | null;
  /** Lowest field value over the last n periods. */
  lowest(field: 'open' | 'high' | 'low' | 'close', n: number): number | null;
  /** Average period turnover over the last n periods (each period sums daily turnover). */
  avgAmount(n: number): number | null;
  /** Average period volume over the last n periods (each period sums daily volume). */
  avgVol(n: number): number | null;
  /** Wilder ADX trend strength with positive/negative directional indicators; defaults to 14 periods. */
  adx(period?: number): { readonly adx: number; readonly positiveDi: number; readonly negativeDi: number } | null;
  /** Bollinger Bands over closes; defaults to 20 periods and two population standard deviations. */
  bollingerBands(period?: number, standardDeviations?: number): { readonly middle: number; readonly upper: number; readonly lower: number } | null;
  /** Wilder RSI in [0, 100], defaulting to 14 periods; a flat window returns 50. */
  rsi(period?: number): number | null;
  /** MACD line, signal, and histogram; defaults to 12/26/9 and does not double the histogram. */
  macd(fastPeriod?: number, slowPeriod?: number, signalPeriod?: number): { readonly line: number; readonly signal: number; readonly histogram: number } | null;
  /** KDJ stochastic oscillator; defaults to 9/3/3 with K/D seeded at 50. */
  kdj(period?: number, kSmoothing?: number, dSmoothing?: number): { readonly k: number; readonly d: number; readonly j: number } | null;
}

export interface FutureBar {
  code: string;
  actualCode: string;
  open: number | null;
  high: number | null;
  low: number | null;
  close: number | null;
  settle: number | null;
  volume: number | null;
  amount: number | null;
  openInterest: number | null;
  multiplier: number;
}

export interface FuturePosition {
  code: string;
  actualCode: string;
  contracts: number;
  margin: number;
}

export interface StrategyAccounts {
  stock: { cashWeight: number };
  futures: { cashWeight: number };
}

export type Schedule = 'daily' | 'weekly' | 'monthly';

export type FactorKey = string;

/** Today's full row for a code: raw + adjusted OHLC + a point-in-time valuation snapshot (the `b` in universe rankBy/where). */
export interface BarRow {
  /** Stock code. */
  code: string;
  /** Point-in-time security name effective on this trading day; null when unavailable. */
  name: string | null;
  /** Whether the stock was under an ST, *ST, or equivalent risk warning on this day. */
  riskWarning: boolean;
  /** Whether the stock was in a delisting-period naming state on this day. */
  pendingDelisting: boolean;
  /** Raw (unadjusted) open. */
  open: number | null;
  /** Raw high. */
  high: number | null;
  /** Raw low. */
  low: number | null;
  /** Raw close. */
  close: number | null;
  /** hfq open. */
  adjOpen: number | null;
  /** hfq high. */
  adjHigh: number | null;
  /** hfq low. */
  adjLow: number | null;
  /** hfq close. */
  adjClose: number | null;
  /** Volume (手). */
  vol: number | null;
  /** Turnover (千元) — liquidity / slippage gate. */
  amount: number | null;
  /** P/E. */
  pe: number | null;
  /** P/E (TTM). */
  peTtm: number | null;
  /** P/B. */
  pb: number | null;
  /** P/S. */
  ps: number | null;
  /** P/S (TTM). */
  psTtm: number | null;
  /** Dividend yield %. */
  dvRatio: number | null;
  /** Dividend yield (TTM) %. */
  dvTtm: number | null;
  /** Total market cap (10k yuan). */
  totalMv: number | null;
  /** Float market cap (10k yuan). */
  circMv: number | null;
  /** Turnover rate %. */
  turnoverRate: number | null;
  /** ROE % (point-in-time). */
  roe: number | null;
  /** Weighted average ROE %. */
  roeWaa: number | null;
  /** ROA % (point-in-time). */
  roa: number | null;
  /** Gross profit margin % (point-in-time). */
  grossprofitMargin: number | null;
  /** Debt-to-assets ratio % (point-in-time). */
  debtToAssets: number | null;
}

/** Today's tradable candidate pool — a chainable filter / rank / slice. */
export interface Universe {
  /** Keep codes whose today-row passes the predicate. */
  where(pred: (bar: BarRow, code: string) => boolean): Universe;
  /** Keep codes listed at least `days` calendar days (point-in-time age). */
  minListDays(days: number): Universe;
  /** Drop the bottom `frac` by `key` (e.g. liquidity floor). */
  dropBottom(frac: number, key: (bar: BarRow, code: string) => number): Universe;
  /** Rank by a score (null-scoring dropped). dir default desc. */
  rankBy(score: (bar: BarRow, code: string) => number | null, dir?: 'desc' | 'asc'): Universe;
  /** Leading slice: a fraction when n<1 (0.1=top decile), else a count. */
  top(n: number): string[];
  /** The current codes after the chain. */
  codes(): string[];
  readonly length: number;
}

/** What the strategy sees and acts through on each bar — every ctx.xxx below is its method (read data, compute indicators, place orders); ctx is always "today". */
export interface StrategyCtx<Params extends StrategyParams = StrategyParams> {
  readonly date: string;
  readonly cash: number;
  readonly value: number;
  readonly availableCash: number;
  readonly stockValue: number;
  readonly futureValue: number;
  readonly stockAvailableCash: number;
  readonly futureAvailableCash: number;
  readonly futureMargin: number;
  readonly params: Readonly<WidenStrategyParams<Params>>;
  /** Today's tradable universe (chainable). Pass an index code to restrict to its point-in-time constituents. */
  universe(indexCode?: string): Promise<Universe>;
  /** Today's full row for a code (valid after universe() loaded the panel), else null. */
  bar(code: string): BarRow | null;
  /** Point-in-time constituents of an index as of today. */
  indexMembers(indexCode: string): Promise<string[]>;
  /** Read-only, point-in-time index handle: close/PE/PB are as-of today; percentile('pe', 2520) ranks today's PE within roughly ten trading years and returns 0..1 (all available history when omitted); sma(n) is the index close MA. */
  index(indexCode: string): { readonly close: number | null; readonly pe: number | null; readonly peTtm: number | null; readonly pb: number | null; sma(n: number): number | null; percentile(field: 'pe' | 'peTtm' | 'pb', lookback?: number): number | null };
  /** Today's futures bar for an actual or main-continuous code; continuous codes resolve point-in-time to an actual contract. */
  future(code: string): FutureBar | null;
  /** Last n futures values, point-in-time mapped each day, oldest to newest. */
  futureHistory(code: string, field: 'open' | 'high' | 'low' | 'close' | 'settle', n: number): number[];
  /** Current futures position; positive contracts are long and negative contracts are short. */
  futurePosition(code: string): FuturePosition | null;
  /** Point-in-time SW level-1 industry label effective on the decision date; null without a covering spell. For sector-neutral or rotation logic without classification lookahead. */
  industry(code: string): string | null;
  /** Today's 龙虎榜 net buy amount (yuan); null if not listed that day (never carried forward). */
  lhbNet(code: string): number | null;
  /** Opt-in factor column for today (declare in `factors`). Moneyflow: 'mf_net_main' / 'mf_net_total' (万元, exact day). A published factor runs by its immutable key on the fly (windowed ones need ensureBars first). A time-series factor declaring etf.adjustedClose accepts ETF codes only. */
  factor(name: FactorKey, code: string): number | null;
  /** Today's adjusted (hfq) close (carried forward if suspended). */
  price(code: string): number | null;
  /** Last n adjusted prices (a field) for held/loaded codes. */
  history(code: string, field: 'open' | 'high' | 'low' | 'close', n: number): number[];
  /** Last n adjusted OHLC bars (Donchian / ATR etc.). */
  bars(code: string, n: number): OhlcBar[];
  /** Completed ISO-week bars and indicators; excludes the current partial week. The instrument bars must be loaded first. */
  weekly(code: string): TimeframeSeries;
  /** Completed natural-month bars and indicators; excludes the current partial month. The instrument bars must be loaded first. */
  monthly(code: string): TimeframeSeries;
  /** Lazily load bar series for codes so bars()/history()/indicators work on them this bar. */
  ensureBars(codes: string[]): Promise<void>;
  /** Calendar days since listing as of today; null if unknown. */
  listDays(code: string): number | null;
  /** n-day simple moving average. */
  sma(code: string, n: number): number | null;
  /** n-day exponential moving average. */
  ema(code: string, n: number): number | null;
  /** n-day ATR (average true range). */
  atr(code: string, n: number): number | null;
  /** Highest of a field over n bars (Donchian upper). */
  highest(code: string, field: 'open' | 'high' | 'low' | 'close', n: number): number | null;
  /** Lowest of a field over n bars (Donchian lower). */
  lowest(code: string, field: 'open' | 'high' | 'low' | 'close', n: number): number | null;
  /** n-day average turnover (千元) — liquidity gate. */
  avgAmount(code: string, n: number): number | null;
  /** n-day average volume (手). */
  avgVol(code: string, n: number): number | null;
  /** Wilder ADX trend strength with positive/negative directional indicators; defaults to 14 days. */
  adx(code: string, period?: number): { readonly adx: number; readonly positiveDi: number; readonly negativeDi: number } | null;
  /** Bollinger Bands over closes; defaults to 20 days and two population standard deviations. */
  bollingerBands(code: string, period?: number, standardDeviations?: number): { readonly middle: number; readonly upper: number; readonly lower: number } | null;
  /** Wilder RSI in [0, 100], defaulting to 14 days; a flat window returns 50. */
  rsi(code: string, period?: number): number | null;
  /** MACD line, signal, and histogram; defaults to 12/26/9, with histogram = line - signal and no doubling. */
  macd(code: string, fastPeriod?: number, slowPeriod?: number, signalPeriod?: number): { readonly line: number; readonly signal: number; readonly histogram: number } | null;
  /** KDJ stochastic oscillator; defaults to 9/3/3 with K/D seeded at 50. */
  kdj(code: string, period?: number, kSmoothing?: number, dSmoothing?: number): { readonly k: number; readonly d: number; readonly j: number } | null;
  /** Period key for today — compare to a `let last` to fire once per period. */
  period(schedule: Schedule): string;
  /** Current shares held of a code (0 if none). */
  shares(code: string): number;
  /** All current positions (code / shares / avgCost / marketValue). */
  positions(): { code: string; shares: number; avgCost: number; marketValue: number }[];
  /** Equal-weight the codes (a target-book rebalance at next open). */
  equalWeight(codes: string[]): void;
  /** ATR risk-sized adjusted shares: a one-ATR adverse move is about current equity × riskPct; defaults to ATR20 and actual buys remain rounded to real 100-share lots. */
  atrUnits(code: string, riskPct: number, atrPeriod?: number): number;
  /** Inverse-volatility weights from recent daily returns; defaults to 20 days, omits insufficient histories, and normalizes remaining weights to 1. Bars must be loaded first. */
  volTargetWeights(codes: string[], lookback?: number): Map<string, number>;
  /** Declarative target weight in [0, 1] for the next-open rebalance; the full target book must sum to at most 1. */
  orderTargetPercent(code: string, weight: number): void;
  /** Declarative target book (code → weight); every weight must be in [0, 1] and the sum at most 1. */
  setHoldings(weights: Record<string, number>): void;
  /** Imperative share order: +buy / -sell, filled at next open. */
  order(code: string, shares: number): void;
  /** Order whole real-share lots (100 shares each); positive buys and negative sells fill next open. */
  orderLots(code: string, lots: number): void;
  /** Sell the entire current position. */
  exit(code: string): void;
  /** Persistent stop loss: from the next trading day, sell all eligible shares when the low reaches the trigger; gaps fill at open. */
  stopLoss(code: string, price: number): void;
  /** Persistent trailing stop (0.08 = 8%); today's trigger uses only the high-water mark known before the bar. */
  trailingStop(code: string, pct: number): void;
  /** Persistent limit buy: eligible from the next trading day and fills when the low reaches the limit, never above it. */
  limitBuy(code: string, price: number, shares: number): void;
  /** Persistent take-profit from current position cost (0.2 = +20%); sells all eligible shares when reached. */
  takeProfit(code: string, pct: number): void;
  /** Cancel one conditional-order kind for a code, or all conditional orders for that code when kind is omitted. */
  cancelConditional(code: string, kind?: 'stop_loss' | 'trailing_stop' | 'limit_buy' | 'take_profit'): void;
  /** Signed integer futures order: +buy / -sell, filled at next open; declare the code in futures. */
  orderFuture(code: string, contracts: number): void;
  /** Set the signed futures contract target for the next open. */
  setFutureTargetContracts(code: string, contracts: number): void;
  /** Set the signed futures notional target for the next open. */
  setFutureTargetNotional(code: string, notional: number): void;
  /** Hedge actual filled stock exposure at the next open; beta=1 requests a full short hedge. */
  hedgeFuture(code: string, beta?: number): void;
  /** Close the entire futures position at the next open. */
  exitFuture(code: string): void;
}

export type StrategyParamValue = number | string;
export type StrategyParams = Record<string, StrategyParamValue>;
export type WidenStrategyParams<Params extends StrategyParams> = {
  [Key in keyof Params]: Params[Key] extends number ? number : string;
};

export interface CodeStrategy<Params extends StrategyParams = StrategyParams> {
  name?: string;
  /** Finite numeric or non-empty categorical defaults exposed to parameter scans. */
  params?: Params;
  /** Opt-in factor columns, read via ctx.factor(): moneyflow columns + published factor keys. */
  factors?: FactorKey[];
  /** Instruments to preload bar series for up front (per-instrument systems). */
  watch?: string[];
  /** Stock-index futures codes to preload. */
  futures?: string[];
  /** Initial capital split for a mixed stock/futures strategy; weights must sum to 1. */
  accounts?: StrategyAccounts;
  onBar(ctx: StrategyCtx<Params>): void | Promise<void>;
}

/** Define a strategy: export default defineStrategy({ onBar(ctx) { … } }). */
export type DefineStrategy = <const Params extends StrategyParams = Record<string, never>>(
  s: CodeStrategy<Params>,
) => void;
